name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  # Build Python package
  build:
    uses: ewoks-kit/.github/.github/workflows/python-build.yml@main

  # Run tests
  tests:
    needs: build
    uses: ewoks-kit/.github/.github/workflows/python-tests.yml@main
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      pytest-args: >-
        -v -ra -W error
        ${{ matrix.extra-pytest-warnings }}
      enable-coverage: ${{ matrix.enable-coverage }}
      jupyter-platform-dirs: "1"
      codecov-flags: "unit"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.8"
            enable-coverage: "false"

          - os: ubuntu-latest
            python-version: "3.9"
            enable-coverage: "false"

          - os: ubuntu-latest
            python-version: "3.10"
            enable-coverage: "false"

          - os: ubuntu-latest
            python-version: "3.11"
            enable-coverage: "false"

          - os: ubuntu-latest
            python-version: "3.12"
            enable-coverage: "true"

          - os: ubuntu-latest
            python-version: "3.13"
            enable-coverage: "false"

          - os: ubuntu-latest
            python-version: "3.14"
            enable-coverage: "false"

          - os: windows-latest
            python-version: "3.9"
            enable-coverage: "false"

  # Run linter / checks
  checks:
    uses: ewoks-kit/.github/.github/workflows/python-check.yml@main

  # Build documentation
  docs:
    needs: build
    uses: ewoks-kit/.github/.github/workflows/python-docs.yml@main